export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

// NEWSLETTER ACTIONS
export const SET_NEWSLETTERS = 'SET_NEWSLETTERS';
export const FETCH_NEWSLETTER_ID = 'FETCH_NEWSLETTER_ID';

// REQUESTS ACTIONS 
export const CHANGE_SELECTED_REQUEST_TYPE = 'CHANGE_SELECTED_REQUEST_TYPE';
export const SET_REQUESTS = 'SET_REQUESTS';